# Generated by Django 3.2.12 on 2022-04-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='swiper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='轮播图id')),
                ('img', models.ImageField(upload_to='banner', verbose_name='轮播图')),
                ('name', models.CharField(max_length=32, verbose_name='轮播图名称')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
