# Generated by Django 3.2.12 on 2022-04-07 21:37

from django.db import migrations, models
import wxxxc.methods.storage


class Migration(migrations.Migration):

    dependencies = [
        ('wxxxc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiper',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        migrations.AlterField(
            model_name='swiper',
            name='img',
            field=models.ImageField(storage=wxxxc.methods.storage.ImageStorage(), upload_to='banner', verbose_name='轮播图'),
        ),
    ]
