# Generated by Django 3.2.12 on 2022-04-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxxxc', '0002_auto_20220407_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='wxuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('openid', models.CharField(max_length=64, verbose_name='用户openid')),
                ('nickname', models.CharField(max_length=64, verbose_name='用户昵称')),
                ('arvatar', models.CharField(max_length=256, verbose_name='用户头像')),
                ('session_key', models.CharField(max_length=64, verbose_name='会话密钥')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后登录时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
