# Generated by Django 3.2.12 on 2022-04-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxxxc', '0003_wxuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxxcConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=50, verbose_name='小程序appid')),
                ('secret', models.CharField(max_length=50, verbose_name='小程序secret')),
                ('access_token', models.CharField(max_length=128, verbose_name='小程序access_token')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('user_count', models.IntegerField(default=0, verbose_name='用户数量')),
            ],
            options={
                'verbose_name': '小程序配置',
                'verbose_name_plural': '小程序配置',
            },
        ),
    ]
