# Generated by Django 3.2.13 on 2022-04-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxxxc', '0004_wxxcconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WxxcConfig',
        ),
    ]
