# Generated by Django 3.2.13 on 2022-04-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxxxc', '0006_wxxcconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='openid',
            field=models.CharField(max_length=128, verbose_name='用户openid'),
        ),
    ]
