# Generated by Django 3.2.13 on 2022-04-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxxxc', '0007_alter_wxuser_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='session_key',
            field=models.CharField(max_length=128, verbose_name='会话密钥'),
        ),
    ]
