# Generated by Django 3.2.13 on 2022-04-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxxxc', '0008_alter_wxuser_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('content', models.CharField(max_length=256, verbose_name='留言内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxxxc.wxuser', verbose_name='用户id')),
            ],
        ),
    ]
