# Generated by Django 3.2.13 on 2022-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxxxc', '0009_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_id',
            field=models.CharField(max_length=128, verbose_name='留言用户openid'),
        ),
    ]
