# Generated by Django 3.2.13 on 2022-04-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxxxc', '0010_alter_message_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_id',
            field=models.CharField(db_column='message_user_id', max_length=128, verbose_name='留言用户openid'),
        ),
    ]
