# Generated by Django 3.2.13 on 2022-04-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxxxc', '0011_alter_message_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '留言', 'verbose_name_plural': '留言'},
        ),
        migrations.AddField(
            model_name='message',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name='是否回复'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='回复内容'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回复时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='留言时间'),
        ),
    ]
