# Generated by Django 3.2.13 on 2022-04-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxxxc', '0012_auto_20220414_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
