# Generated by Django 3.2.13 on 2022-04-25 11:13

from django.db import migrations, models
import wxxcx.methods.storage


class Migration(migrations.Migration):

    dependencies = [
        ('wxxcx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('user_id', models.CharField(db_column='message_user_id', max_length=128, verbose_name='留言用户openid')),
                ('content', models.CharField(max_length=256, verbose_name='留言内容')),
                ('img', models.CharField(max_length=256, verbose_name='留言图片(列表)')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('is_reply', models.BooleanField(default=False, verbose_name='是否回复')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('reply', models.CharField(blank=True, max_length=256, null=True, verbose_name='回复内容')),
                ('reply_time', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='通知id')),
                ('title', models.CharField(max_length=32, verbose_name='通知标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='通知内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
            },
        ),
        migrations.CreateModel(
            name='swiper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='轮播图id')),
                ('img', models.ImageField(storage=wxxcx.methods.storage.ImageStorage(), upload_to='banner', verbose_name='轮播图')),
                ('name', models.CharField(max_length=32, verbose_name='轮播图名称')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='wxuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('openid', models.CharField(max_length=128, verbose_name='用户openid')),
                ('nickname', models.CharField(max_length=64, verbose_name='用户昵称')),
                ('arvatar', models.CharField(max_length=256, verbose_name='用户头像')),
                ('session_key', models.CharField(max_length=128, verbose_name='会话密钥')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后登录时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='WxxcConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('key', models.CharField(max_length=50, verbose_name='配置键')),
                ('value', models.CharField(max_length=128, verbose_name='配置值')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '小程序配置',
                'verbose_name_plural': '小程序配置',
            },
        ),
    ]
