# Generated by Django 3.2.13 on 2022-04-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxxcx', '0002_message_notice_swiper_wxuser_wxxcconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message_img',
        ),
    ]
