# Generated by Django 3.2.13 on 2022-04-25 11:19

from django.db import migrations, models
import wxxcx.methods.storage


class Migration(migrations.Migration):

    dependencies = [
        ('wxxcx', '0003_delete_message_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_img',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('message_id', models.CharField(max_length=128, verbose_name='留言id')),
                ('img', models.ImageField(storage=wxxcx.methods.storage.ImageStorage(), upload_to='message', verbose_name='留言图片')),
            ],
            options={
                'verbose_name': '留言图片',
                'verbose_name_plural': '留言图片',
            },
        ),
    ]
