# Generated by Django 3.2.13 on 2022-04-22 23:50

from django.db import migrations, models
import vueqd.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('avatar', models.ImageField(max_length=200, storage=vueqd.storage.ImageStorage(), upload_to='avatar', verbose_name='用户头像')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后登录时间')),
                ('is_login', models.BooleanField(default=False, verbose_name='是否在登录')),
                ('token', models.CharField(max_length=125, verbose_name='token')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
